spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084
